### ISSUE TITLE
[!] Invalid `Podfile` file: [!] The specification of `link_with` in the Podfile is now unsupported, please use target blocks instead..

### ISSUE THREAD

**Issue by yupliang** [paweldudek/bdd-examples#1]
sorry for disturbing you , but i got a problem when i use your Bdd example workspace.Could you please update your  Podfile? the error is like below 
```
[!] Invalid `Podfile` file: [!] The specification of `link_with` in the Podfile is now unsupported, please use target blocks instead..
```

**Comment by paweldudek** [comment]
I've updated project to latest versions of Cocoapods, Xcode and iOS SDK. Enjoy!
